package store

import "encoding/json"

// seed_showcase.go —— 「产品官网」样板内容。
// 目的：让首次安装后的默认站点就是 gcms 的标准产品官网样板。

type seedNavRow struct {
	URL    string            `json:"url"`
	Labels map[string]string `json:"labels"`
}

type seedSocialRow struct {
	URL   string `json:"url"`
	Label string `json:"label"`
}

func seedJSON(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}

// seedShowcase 写入产品营销向的样板：站点身份、首页、关于页、双语特性文、实用教程 + 生态链接。
func (s *Store) seedShowcase() error {
	// ---- 站点身份（产品定位，中英双语）----
	_ = s.SetSetting("site.name", "gcms")
	_ = s.SetSetting("site.tagline", "内容发布、搜索增长，一个后台跑通")
	_ = s.SetSetting("site.description", "gcms 把文章、页面、资源链接、全语种内容、主题、SEO/GEO、在线升级和 AI 自运营接口收进同一个后台；无需搭数据库服务和前端构建环境，一行命令即可部署，1 vCPU / 512MB 内存的小规格 VPS 也能稳定起步。")
	_ = s.SetSetting("site.hero_eyebrow", "轻部署 · SEO/GEO 就绪 · AI 自运营")
	_ = s.SetSetting("site.hero_title", "内容发布、\n搜索增长，\n一个后台跑通")
	_ = s.SetSetting("site.footer_note", "gcms · 单文件部署的自托管内容系统")
	_ = s.SetSetting("site.tagline::en", "Publish content and grow search from one admin")
	_ = s.SetSetting("site.description::en", "gcms brings posts, pages, resource links, multilingual content, themes, SEO/GEO, in-app updates and AI-operation APIs into one lightweight admin. No database server or frontend build pipeline required: deploy with one command and start on a 1 vCPU / 512MB VPS.")
	_ = s.SetSetting("site.hero_eyebrow::en", "Self-hosted · SEO/GEO-ready · AI operations")
	_ = s.SetSetting("site.hero_title::en", "Publish content,\ngrow search traffic,\nrun it from one admin")
	_ = s.SetSetting("site.footer_note::en", "gcms · self-hosted content in one deployable file")

	_ = s.SetSetting("home.featured_title", "先看这几件事")
	_ = s.SetSetting("home.links_title", "下载与生态入口")
	_ = s.SetSetting("home.latest_title", "更多能力说明")
	_ = s.SetSetting("home.featured_title::en", "Start Here")
	_ = s.SetSetting("home.links_title::en", "Downloads & Ecosystem")
	_ = s.SetSetting("home.latest_title::en", "More Capabilities")

	_ = s.SetSetting("category.all.title", "功能与指南")
	_ = s.SetSetting("category.all.label", "全部")
	_ = s.SetSetting("category.all.slug", "category")
	_ = s.SetSetting("category.all.description", "从部署、SEO、多语种、写作体验到实用教程，快速了解 gcms 如何把一个内容站做成低维护、可增长的产品入口。")
	_ = s.SetSetting("category.all.title::en", "Features & Guides")
	_ = s.SetSetting("category.all.label::en", "All")
	_ = s.SetSetting("category.all.slug::en", "category")
	_ = s.SetSetting("category.all.description::en", "From deployment and SEO to i18n, editing and hands-on guides, see how gcms turns a content site into a low-maintenance product entry point.")
	_ = s.SetSetting("links.all.title", "下载与资源")
	_ = s.SetSetting("links.all.label", "全部")
	_ = s.SetSetting("links.all.slug", "links")
	_ = s.SetSetting("links.all.description", "发布包、一键安装、线上演示和核心技术栈都在这里，评估与部署不用四处找入口。")
	_ = s.SetSetting("links.all.title::en", "Downloads & Resources")
	_ = s.SetSetting("links.all.label::en", "All")
	_ = s.SetSetting("links.all.slug::en", "links")
	_ = s.SetSetting("links.all.description::en", "Release packages, one-line install, live demo and the core stack behind gcms, collected in one place.")

	// 产品官网气质：用 product 主题；页眉仅显示 Logo，便于用户替换品牌图形。
	_ = s.SetSetting("theme", "product")
	_ = s.SetSetting("site.brand", "logo")
	_ = s.SetSetting("site.share_image", "/assets/og-cover.webp")
	_ = s.SetSetting("site.share_image::en", "/assets/og-cover-en.webp")
	_ = s.SetSetting("hero.visual", "image")
	_ = s.SetSetting("hero.image", "/assets/hero-product-overview-brand.webp")
	_ = s.SetSetting("hero.visual::en", "image")
	_ = s.SetSetting("hero.image::en", "/assets/hero-product-overview-brand-en.webp")
	_ = s.SetSetting("hero.svg", "")
	_ = s.SetSetting("nav_menu", seedJSON([]seedNavRow{
		{URL: "/", Labels: map[string]string{"zh": "首页", "en": "Home"}},
		{URL: "/category/features", Labels: map[string]string{"zh": "功能", "en": "Features"}},
		{URL: "/category/guides", Labels: map[string]string{"zh": "指南", "en": "Guides"}},
		{URL: "/links", Labels: map[string]string{"zh": "资源", "en": "Resources"}},
		{URL: "/start", Labels: map[string]string{"zh": "开始使用", "en": "Get Started"}},
	}))
	_ = s.SetSetting("social_links", seedJSON([]seedSocialRow{
		{URL: "https://github.com/ccvar/gcms-releases", Label: "Releases"},
		{URL: "https://ccvar.com", Label: "Demo"},
		{URL: "/rss.xml", Label: "RSS"},
	}))
	_ = s.SetSetting("demo.seed", "showcase")

	// 多语种 + 管理员
	_ = s.SetSetting("locales", "zh,en")
	_ = s.SetSetting("default_lang", "zh")
	_ = s.SetSetting("admin_user", "admin")
	if hash, err := bcryptHash(DefaultAdminPassword); err == nil {
		_ = s.SetSetting("admin_password_hash", hash)
	}

	// ---- 文章分类：特性支柱（中英各一套）----
	cats := []seedCat{
		{"start", "快速上手", "从下载、启动到 Caddy 上线，走完一次真实部署。", "zh", "s-cat-start", "post"},
		{"features", "核心能力", "SEO、多语种、主题、编辑器与可视化配置，决定一个内容站能否长期省心。", "zh", "s-cat-features", "post"},
		{"guides", "实用教程", "用真实后台截图讲清楚换主题、AI 运营、可视化编辑、导航配置与首装安全。", "zh", "s-cat-guides", "post"},
		{"ops", "运维与自动化", "在线更新、开放接口和 AI 友好的接入文件，让后期维护不再靠记命令。", "zh", "s-cat-ops", "post"},
		{"start", "Getting Started", "Download, run and put gcms behind Caddy in one real deployment path.", "en", "s-cat-start", "post"},
		{"features", "Core Features", "SEO, i18n, themes, editing and visual configuration, built for long-term low maintenance.", "en", "s-cat-features", "post"},
		{"guides", "How-to Guides", "Real admin screenshots for changing themes, AI-assisted ops, visual editing, navigation setup and first-install safety.", "en", "s-cat-guides", "post"},
		{"ops", "Ops & Automation", "In-app updates, open APIs and AI-friendly integration files, without command-memory maintenance.", "en", "s-cat-ops", "post"},
	}
	catID := map[string]map[string]int64{"zh": {}, "en": {}}
	for _, c := range cats {
		res, err := s.db.Exec(`INSERT INTO categories(slug,name,description,position,lang,trans_group,kind) VALUES(?,?,?,?,?,?,?)`,
			c.Slug, c.Name, c.Description, len(catID[c.Lang]), c.Lang, c.Group, "post")
		if err != nil {
			return err
		}
		id, _ := res.LastInsertId()
		catID[c.Lang][c.Slug] = id
	}

	posts := showcasePosts()
	for _, sp := range posts {
		if err := s.insertSeed(sp, catID[sp.Lang]); err != nil {
			return err
		}
	}

	// ---- 关于页（产品电梯演讲，中英双语）----
	for _, sp := range showcaseAbouts() {
		if err := s.insertSeed(sp, catID[sp.Lang]); err != nil {
			return err
		}
	}

	// ---- 链接分类（kind=link）----
	linkCats := []seedCat{
		{"project", "项目入口", "正式站点、发布包与安装入口。", "zh", "s-lcat-project", "link"},
		{"stack", "核心技术", "支撑 gcms 单文件部署与生产运行的关键技术。", "zh", "s-lcat-stack", "link"},
		{"project", "Project Entry", "Official site, release packages and install entry points.", "en", "s-lcat-project", "link"},
		{"stack", "Core Stack", "The key technologies behind gcms's one-file deployment and production runtime.", "en", "s-lcat-stack", "link"},
	}
	linkCatID := map[string]map[string]int64{"zh": {}, "en": {}}
	for _, c := range linkCats {
		res, err := s.db.Exec(`INSERT INTO categories(slug,name,description,position,lang,trans_group,kind) VALUES(?,?,?,?,?,?,?)`,
			c.Slug, c.Name, c.Description, len(linkCatID[c.Lang]), c.Lang, c.Group, "link")
		if err != nil {
			return err
		}
		id, _ := res.LastInsertId()
		linkCatID[c.Lang][c.Slug] = id
	}

	for _, sp := range showcaseLinks() {
		if err := s.insertSeed(sp, linkCatID[sp.Lang]); err != nil {
			return err
		}
	}

	s.Seeded = true
	return nil
}

// showcasePosts 返回双语特性文与实用教程（按 trans_group 关联中英版本）。
func showcasePosts() []seedPost {
	return []seedPost{
		// ===== 1 · 旗舰：5 分钟部署（start，置顶）=====
		{
			Slug: "deploy-in-5-minutes", Title: "5 分钟上线一个真正可用的内容站",
			Excerpt:  "下载、运行、打开后台。数据库、模板、SEO、多语种和主题都已经装好，剩下的只是把它放到你的域名后面。",
			MetaDesc: "用 gcms 自托管一个完整内容站：单个二进制启动，SQLite 单文件存储，用 Caddy 反代 HTTPS，5 分钟完成首次上线。",
			Keywords: "gcms,自托管,部署,单文件,Go,SQLite,轻量CMS", Author: "gcms", Cat: "start", Date: "2026-06-12",
			Lang: "zh", Group: "s-deploy-5min", Featured: true, Cover: "/assets/covers/release-package-real.webp",
			Content: md(
				"你现在浏览的这个站，就是一个 **gcms** 实例。它不是静态截图，也不是前端 Demo，而是单个静态二进制 + 一个 SQLite 数据库文件跑出来的真实站点。第一次部署只需要三步。",
				"",
				"![gcms 发布包下载页真实截图：选择平台包、校验文件与一键安装脚本](/assets/covers/release-package-real.webp)",
				"",
				"## 第一步 · 拿到二进制",
				"",
				"到 [发布页](https://github.com/ccvar/gcms-releases/releases/latest) 下载对应平台的包（linux / macOS / windows，amd64 / arm64 都有），解压即可。里面已经包含预编译好的 `bin/cms`、启停脚本和默认配置——**部署机上不需要安装 Go，也不需要跑前端构建**。",
				"",
				"如果你想直接在新机器上安装，也只要一行：",
				"",
				"~~~bash",
				"curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh \\",
				"  | sh",
				"~~~",
				"",
				"## 第二步 · 运行",
				"",
				"~~~bash",
				"./bin/cms",
				"# 或后台运行：",
				"./scripts/cms.sh start",
				"# → http://localhost:8080   后台 /admin",
				"~~~",
				"",
				"首次启动会自动建好数据库、写入演示内容，并在控制台**打印默认后台账号**（`admin / admin123`）。登录后第一件事，就是去「设置 → 安全」改掉它——首页那条提醒也会一直挂着，直到你改完。",
				"",
				"## 第三步 · 上线",
				"",
				"生产环境让 gcms 只监听回环地址，把 HTTPS、压缩、HTTP/3 交给 [Caddy](https://caddyserver.com)。正式站点可以直接设为你的域名，例如 `https://ccvar.com`：",
				"",
				"~~~bash",
				"ADDR=127.0.0.1:8080 \\",
				"BASE_URL=https://ccvar.com \\",
				"./scripts/cms.sh start",
				"~~~",
				"",
				"~~~caddyfile",
				"ccvar.com {",
				"    encode zstd gzip",
				"    reverse_proxy 127.0.0.1:8080",
				"}",
				"~~~",
				"",
				"`caddy run`，证书自动签发。完事。",
				"",
				"## 它已经替你做好了这些",
				"",
				"上线的同时，下面这些**默认就位**，不用额外配置：",
				"",
				"- **原生 SEO**：每页服务端渲染，自带 canonical、`hreflang`、Open Graph、`sitemap.xml`、RSS 与 JSON-LD 结构化数据；",
				"- **多语种**：URL 前缀路由（`/zh/…`、`/en/…`），逐语种维护内容，自动输出 hreflang 备份链接；",
				"- **18 套主题**：后台一键切换，还能按主题微调主色与圆角；",
				"- **双模式编辑器**：Markdown ⇄ 所见即所得，粘贴图片、插表格、拖动段落；",
				"- **链接展示、代码注入、社媒页脚、自定义导航、后台在线更新**……",
				"",
				"## 环境要求",
				"",
				"gcms 的运行形态很轻，小规格 VPS 就能承载一个产品官网或资料站：",
				"",
				"- **CPU**：1 vCPU 即可启动和日常运行；",
				"- **内存**：512MB 级别机器可以部署，内容量和并发升高后再按需加；",
				"- **磁盘**：程序包很小，主要增长来自 SQLite 数据库、上传图片和日志；",
				"- **系统**：linux、macOS、Windows 都有预编译包，支持 amd64 / arm64；",
				"- **公网入口**：生产环境推荐 Caddy 监听 80/443，gcms 只监听 `127.0.0.1:8080`。",
				"",
				"换句话说，它不要求你先准备一整套数据库、缓存、前端构建和进程编排。你只需要一台能跑二进制的小机器，和一个愿意被认真维护的内容计划。",
				"",
				"## 适合哪些场景",
				"",
				"gcms 最适合那些「内容很重要，但不想把维护做重」的网站：产品官网、开源项目官网、技术文档、课程资料站、资源导航、独立博客和小团队知识库。它不是一个大型协同平台，却很适合做一个**长期稳定、SEO 友好、随时能迁移**的内容入口。",
				"",
				"> 把复杂留在编译期，把简单交给运行时——这套架构最值钱的一句话。",
				"",
				"## 为什么能这么简单",
				"",
				"因为只有两个「单数」：Go 用 `embed.FS` 把模板和静态资源**焊进一个二进制**，SQLite 把数据库收敛成**一个文件**。没有独立数据库进程、没有前端构建链、没有运行时依赖。备份就是复制那个 `.db`，迁移就是 `scp` 一个文件。",
				"",
				"五分钟，你就拥有了一个完全属于自己、能被搜索引擎完整收录、还足够好看的内容站。",
			),
		},
		{
			Slug: "deploy-in-5-minutes", Title: "Launch a Real Content Site in 5 Minutes",
			Excerpt:  "Download, run, open the admin. The database, templates, SEO, i18n and themes are already there; put it behind your domain and ship.",
			MetaDesc: "Self-host a complete content site with gcms: start one binary, store data in one SQLite file, put Caddy in front for HTTPS, and launch in minutes.",
			Keywords: "gcms,self-hosted,deploy,single binary,Go,SQLite,lightweight CMS", Author: "gcms", Cat: "start", Date: "2026-06-12",
			Lang: "en", Group: "s-deploy-5min", Featured: true, Cover: "/assets/covers/release-package-real-en.webp",
			Content: md(
				"The site you're reading is a **gcms** instance. Not a static mockup, not a front-end demo: a real site running from one static binary plus one SQLite database file. First deployment is three steps.",
				"",
				"![Real gcms release package screenshot: platform packages, checksum file and install script](/assets/covers/release-package-real-en.webp)",
				"",
				"## Step 1 · Get the binary",
				"",
				"Grab the package for your platform from the [releases page](https://github.com/ccvar/gcms-releases/releases/latest) (linux / macOS / windows, amd64 / arm64) and unpack it. Inside is a prebuilt `bin/cms`, start/stop scripts and a default config — **no Go and no front-end build chain required on the server**.",
				"",
				"To install directly on a fresh machine, it's one line:",
				"",
				"~~~bash",
				"curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh \\",
				"  | sh",
				"~~~",
				"",
				"## Step 2 · Run",
				"",
				"~~~bash",
				"./bin/cms",
				"# Or run it in the background:",
				"./scripts/cms.sh start",
				"# → http://localhost:8080   admin at /admin",
				"~~~",
				"",
				"On first launch it creates the database, writes demo content, and **prints the default admin credentials** (`admin / admin123`). Change them first thing under Settings → Security — a banner keeps nagging until you do.",
				"",
				"## Step 3 · Go live",
				"",
				"In production, bind gcms to loopback and let [Caddy](https://caddyserver.com) handle HTTPS, compression and HTTP/3. Use your real domain for `BASE_URL`, for example `https://ccvar.com`:",
				"",
				"~~~bash",
				"ADDR=127.0.0.1:8080 \\",
				"BASE_URL=https://ccvar.com \\",
				"./scripts/cms.sh start",
				"~~~",
				"",
				"~~~caddyfile",
				"ccvar.com {",
				"    encode zstd gzip",
				"    reverse_proxy 127.0.0.1:8080",
				"}",
				"~~~",
				"",
				"`caddy run`, certificate issued automatically. Done.",
				"",
				"## What's already done for you",
				"",
				"- **SEO-native**: server-rendered pages with canonical, `hreflang`, Open Graph, `sitemap.xml`, RSS and JSON-LD;",
				"- **Multilingual**: URL-prefix routing (`/zh/…`, `/en/…`), per-language content, automatic hreflang alternates;",
				"- **18 themes**, switchable from the admin, with per-theme accent and radius tweaks;",
				"- **Dual-mode editor**: Markdown ⇄ WYSIWYG, paste images, insert tables, drag blocks;",
				"- Link showcase, code injection, social footer, custom nav, in-app updates…",
				"",
				"## Environment requirements",
				"",
				"gcms has a lightweight runtime shape, so a small VPS is enough for a product site or documentation hub:",
				"",
				"- **CPU**: 1 vCPU is enough to start and run normal content workloads;",
				"- **Memory**: a 512MB machine can deploy it; scale up only when content volume or traffic requires it;",
				"- **Disk**: the package is small; growth mostly comes from the SQLite database, uploads and logs;",
				"- **OS**: prebuilt packages exist for linux, macOS and Windows, with amd64 / arm64 variants;",
				"- **Public entry**: in production, let Caddy listen on 80/443 while gcms binds to `127.0.0.1:8080`.",
				"",
				"In other words, you do not need a database cluster, cache layer, front-end build chain or process orchestra before shipping. You need a small machine that can run one binary, and a content plan worth maintaining.",
				"",
				"## Where it fits",
				"",
				"gcms fits sites where content matters but maintenance should stay light: product sites, open-source project sites, technical docs, course material, resource directories, independent blogs and small-team knowledge bases. It is not a large collaboration suite; it is a **stable, SEO-friendly, easy-to-move content entry point**.",
				"",
				"> Keep the complexity at compile time, keep it simple at runtime.",
				"",
				"## Why it's this simple",
				"",
				"Two singulars: Go's `embed.FS` welds templates and assets **into one binary**, and SQLite collapses the database into **one file**. No separate database process, no frontend build chain, no runtime dependencies. Backup is copying that `.db`; migration is `scp`-ing one file.",
				"",
				"Five minutes, and you own a content site that's entirely yours, fully indexable, and good-looking enough to ship.",
			),
		},

		// ===== 2 · 为什么 Go + SQLite（features，置顶）=====
		{
			Slug: "why-go-and-sqlite", Title: "为什么 gcms 能这么轻",
			Excerpt:  "Go 负责把应用收敛成一个二进制，SQLite 负责把数据收敛成一个文件。复杂度少一点，站点就更容易长期维护。",
			MetaDesc: "gcms 选择 Go + SQLite 的理由：单一静态二进制、零运行时依赖、SQLite 单文件数据库，以及读多写少内容站所需的低维护架构。",
			Keywords: "Go,SQLite,架构,单文件,零依赖,WAL", Author: "gcms", Cat: "features", Date: "2026-06-11",
			Lang: "zh", Group: "s-why-go-sqlite", Featured: true, Cover: "/assets/covers/gcms-stack-brand.webp",
			Content: md(
				"内容站的真实需求很朴素：把内容存起来，渲染成 HTML，让读者和爬虫都能稳定读到。gcms 没有把这件事做重，而是用 **Go + SQLite** 把运行形态压到最简单。",
				"",
				"![gcms 技术栈封面：Go 单二进制与 SQLite 单文件数据库组合](/assets/covers/gcms-stack-brand.webp)",
				"",
				"## 一个二进制",
				"Go 把整个应用编译成一个静态可执行文件，`embed.FS` 把模板与静态资源一并打进去。部署没有「装运行时、装依赖、配环境」——上传，运行，结束。交叉编译到任意平台也只是换个 `GOOS`。",
				"",
				"## 一个文件",
				"SQLite 没有独立进程、没有网络往返，读取延迟以微秒计。开启 **WAL** 后读不阻塞写、写不阻塞读，瓶颈只剩「同一时刻一个写者」——对读多写少的内容站，这几乎不构成限制。",
				"",
				"## 一套低维护的取舍",
				"它能在一台很便宜的机器上稳稳服务一个中型站点。备份是复制一个文件，回滚是换回一个文件。在你真正撞上「需要多机共享数据」之前，这套简单就是最划算的架构。",
				"",
				"## 什么时候需要更重的架构",
				"如果你的内容编辑每天都有大量并发写入、需要复杂审批流、需要多机同时写同一份数据，传统数据库和更完整的协同系统会更合适。gcms 的判断是：多数内容站首先需要的是**可部署、可备份、可长期维护**，而不是一开始就把复杂度拉满。",
				"",
				"> 复杂度被压到最低，而该有的能力，一个都不少。",
			),
		},
		{
			Slug: "why-go-and-sqlite", Title: "Why gcms Can Stay This Light",
			Excerpt:  "Go turns the app into one binary; SQLite turns the data into one file. Less moving parts means a site you can maintain for years.",
			MetaDesc: "Why gcms is built on Go + SQLite: a single static binary, zero runtime dependencies, a single-file SQLite database, and low-maintenance architecture for read-heavy content sites.",
			Keywords: "Go,SQLite,architecture,single file,zero dependency,WAL", Author: "gcms", Cat: "features", Date: "2026-06-11",
			Lang: "en", Group: "s-why-go-sqlite", Featured: true, Cover: "/assets/covers/gcms-stack-brand-en.webp",
			Content: md(
				"A content site's real needs are humble: store content, render HTML, let people and crawlers read it reliably. gcms keeps that shape light with **Go + SQLite**.",
				"",
				"![gcms stack cover: Go single binary and SQLite single-file database](/assets/covers/gcms-stack-brand-en.webp)",
				"",
				"## One binary",
				"Go compiles the whole app into one static executable; `embed.FS` bundles templates and assets in. No runtime, no dependency install, no environment config — upload, run, done. Cross-compiling to any platform is just a different `GOOS`.",
				"",
				"## One file",
				"SQLite has no separate process and no network round-trips; read latency is measured in microseconds. With **WAL**, reads don't block writes and writes don't block reads — the only limit is one writer at a time, which a read-heavy content site barely notices.",
				"",
				"## A low-maintenance trade-off",
				"It serves a mid-sized site comfortably on a very cheap box. Backup is copying one file; rollback is swapping it back. Until you genuinely need multi-machine shared data, this simplicity is the better architecture.",
				"",
				"## When a heavier stack is better",
				"If your editors write concurrently at high volume, need complex approval workflows, or require multiple machines to write the same dataset, a traditional database and collaboration suite may fit better. gcms bets that most content sites first need to be **deployable, backup-friendly and maintainable for years**.",
				"",
				"> Complexity squeezed to a minimum, with none of the capability lost.",
			),
		},

		// ===== 3 · 多语种内置（features）=====
		{
			Slug: "multilingual-built-in", Title: "多语种从第一天就准备好",
			Excerpt:  "每个语种都有独立路径、独立内容和自动 hreflang。你不是在翻译一个站，而是在运营多个可被搜索收录的入口。",
			MetaDesc: "gcms 的多语种能力：URL 前缀路由、按语种独立维护内容、自动 hreflang 备份链接、可自定义语种，让每种语言都被对应搜索引擎正确收录。",
			Keywords: "多语种,i18n,hreflang,国际化,SEO,语种", Author: "gcms", Cat: "features", Date: "2026-06-10",
			Lang: "zh", Group: "s-i18n", Cover: "/assets/screenshots/language-switch.webp",
			Content: md(
				"多语种不是把界面文案翻一遍那么简单。真正难的是：**让每种语言的内容都能被对应区域的搜索引擎正确发现与收录**。gcms 从路由到 SEO 都为此设计。",
				"",
				"![gcms 前台语言切换真实截图：中文与 English 可在页面顶部切换](/assets/screenshots/language-switch.webp)",
				"",
				"## 一种语言，一段路径",
				"`/zh/…`、`/en/…`——每种语言有独立的 URL 前缀，甚至可以用各自的 slug。地址语义清晰，分享与收录都干净。",
				"",
				"## 内容逐语种维护",
				"同一篇文章的各语种版本通过「互译分组」关联，可以分别编辑、分别发布、互不打架。某种语言还没译？那一页就只出现在那种语言里，不会有半成品。",
				"",
				"## hreflang 自动输出",
				"每个页面都会自动生成 `hreflang` 备份链接（含 `x-default`），明确告诉搜索引擎「这页还有这些语言版本」，避免重复内容、把流量导向正确的语言。",
				"",
				"## 还能自定义语种",
				"内置一批预设语种，也能在后台新增任意语种——加一门语言，不用改一行代码。",
				"",
				"## 默认语种不是硬跳转",
				"后台设置里的「默认语种」更像兜底规则：当访问者的浏览器语言不在启用语种范围内，就回到默认语种；当路径已经明确是 `/zh/` 或 `/en/` 时，gcms 尊重路径，不强行改走别的语言。这对用户体验和搜索引擎都更稳定。",
				"",
				"> 你正在读的这页，就有一个英文版本。点右上角的语言切换试试。",
			),
		},
		{
			Slug: "multilingual-built-in", Title: "Multilingual from Day One",
			Excerpt:  "Every language gets its own paths, content and hreflang. You're not translating one site; you're running multiple indexable entry points.",
			MetaDesc: "gcms multilingual support: URL-prefix routing, independently maintained per-language content, automatic hreflang alternates, and custom locales — so every language is correctly indexed.",
			Keywords: "multilingual,i18n,hreflang,internationalization,SEO,locale", Author: "gcms", Cat: "features", Date: "2026-06-10",
			Lang: "en", Group: "s-i18n", Cover: "/assets/screenshots/language-switch-en.webp",
			Content: md(
				"Going multilingual isn't just translating the UI. The hard part is making **each language's content discoverable and indexable by the right regional search engine**. gcms is designed for that, from routing to SEO.",
				"",
				"![Real gcms language switcher screenshot: Chinese and English options in the public header](/assets/screenshots/language-switch-en.webp)",
				"",
				"## One language, one path",
				"`/zh/…`, `/en/…` — each language gets its own URL prefix, and can even use its own slugs. Clean to share, clean to index.",
				"",
				"## Content maintained per language",
				"Versions of the same article are linked by a translation group, so you edit and publish each independently. Not translated yet? That page simply doesn't appear in that language — no half-finished stubs.",
				"",
				"## hreflang, automatically",
				"Every page emits `hreflang` alternates (including `x-default`), telling search engines which language versions exist — avoiding duplicate content and routing traffic to the right language.",
				"",
				"## Custom locales too",
				"A set of locales ships built in, and you can add any locale from the admin — a new language without a line of code.",
				"",
				"## Default language is a fallback",
				"The default language is a fallback rule, not a forced redirect. If the visitor's browser language is outside your enabled locales, gcms falls back to the default; if the URL already says `/zh/` or `/en/`, the path wins. That is calmer for users and clearer for search engines.",
				"",
				"> The page you're reading has a Chinese version. Try the language switcher, top right.",
			),
		},

		// ===== 4 · 双模式编辑器（features）=====
		{
			Slug: "dual-mode-editor", Title: "写作不该被编辑器打断",
			Excerpt:  "Markdown 和富文本可以随时切换，图片、表格、段落重排都顺手完成。工具退后，内容往前。",
			MetaDesc: "gcms 的双模式编辑器：Markdown 与所见即所得随时一键切换，支持粘贴图片自动转 WebP、插入与编辑表格、拖动段落重排，写作零阻力。",
			Keywords: "编辑器,Markdown,富文本,所见即所得,WebP,写作", Author: "gcms", Cat: "features", Date: "2026-06-09",
			Lang: "zh", Group: "s-editor", Cover: "/assets/screenshots/article-editor.webp",
			Content: md(
				"写作的阻力越小越好。gcms 的编辑器给你两种手感，随时一键切换，内容无损迁移。",
				"",
				"![gcms 后台新建文章真实截图：标题、正文、语种、状态、封面和 SEO 摘要在同一流程中完成](/assets/screenshots/article-editor.webp)",
				"",
				"## Markdown 模式",
				"纯文本、可预期、对版本管理友好。习惯键盘流的人，从头到尾不用碰鼠标。",
				"",
				"## 富文本模式",
				"所见即所得，而且**间距、字号、标题层级都和前台文章页完全一致**——你在编辑器里看到的样子，就是读者最终看到的样子。",
				"",
				"## 顺手的细节",
				"- 选中文字，工具栏在选区**上方**浮现，不遮挡你正在改的字；",
				"- 粘贴或插入图片自动转 **WebP**，并在**点保存时**才上传，草稿期不留垃圾文件；",
				"- 插入、增删行列地编辑**表格**；",
				"- 抓住段落左侧把手，像整理卡片一样**拖动重排**顺序。",
				"",
				"## 对内容运营的价值",
				"一个好编辑器不是功能越多越好，而是能减少「写完还要修格式」的时间。标题层级清晰、图片有稳定地址、表格能正常渲染，这些细节最后都会落到文章页的可读性、分享效果和搜索收录上。",
				"",
				"> 工具不该挡在你和文字之间。它该隐形。",
			),
		},
		{
			Slug: "dual-mode-editor", Title: "Writing Shouldn't Fight the Editor",
			Excerpt:  "Switch between Markdown and rich text anytime; handle images, tables and block order without leaving the flow.",
			MetaDesc: "gcms's dual-mode editor: switch between Markdown and WYSIWYG anytime, paste images auto-converted to WebP, insert and edit tables, and drag blocks to reorder — writing with zero friction.",
			Keywords: "editor,Markdown,rich text,WYSIWYG,WebP,writing", Author: "gcms", Cat: "features", Date: "2026-06-09",
			Lang: "en", Group: "s-editor", Cover: "/assets/screenshots/article-editor-en.webp",
			Content: md(
				"The less friction in writing, the better. gcms's editor gives you two feels, switchable anytime, with no content loss.",
				"",
				"![Real gcms editor screenshot: title, body, language, status, cover and SEO excerpt in one publishing flow](/assets/screenshots/article-editor-en.webp)",
				"",
				"## Markdown mode",
				"Plain text, predictable, version-control friendly. Keyboard-flow writers never touch the mouse.",
				"",
				"## Rich-text mode",
				"WYSIWYG — and the **spacing, sizes and heading hierarchy match the public article page exactly**. What you see in the editor is what the reader gets.",
				"",
				"## Details that help",
				"- Select text and the toolbar appears **above** the selection, never covering what you're editing;",
				"- Pasted or inserted images are auto-converted to **WebP** and uploaded only **on save**, so drafts leave no orphan files;",
				"- Insert and edit **tables**, adding or removing rows and columns;",
				"- Grab a block's left handle and **drag to reorder**, like rearranging cards.",
				"",
				"## Why it matters for content ops",
				"A good editor is not about piling on controls; it reduces the time spent fixing formatting after writing. Clear heading levels, stable image URLs and tables that render well all feed into readability, sharing quality and search indexing.",
				"",
				"> A tool shouldn't stand between you and your words. It should disappear.",
			),
		},

		// ===== 5 · 原生 SEO（features）=====
		{
			Slug: "seo-by-default", Title: "SEO 不应该等上线后再补",
			Excerpt:  "服务端渲染、canonical、hreflang、sitemap、RSS、JSON-LD 默认生成。你专心写内容，gcms 负责让它被正确发现。",
			MetaDesc: "gcms 默认内置的 SEO 能力：服务端渲染、canonical、多语种 hreflang、sitemap、RSS 与 JSON-LD 结构化数据，开箱即用、自动校验通过。",
			Keywords: "SEO,SSR,hreflang,sitemap,结构化数据,JSON-LD,canonical", Author: "gcms", Cat: "features", Date: "2026-06-08",
			Lang: "zh", Group: "s-seo-default", Cover: "/assets/screenshots/seo-output.webp",
			Content: md(
				"很多站点把 SEO 当成上线后再补的功课。gcms 把它做成了**默认行为**——你写好内容，剩下的它替你处理。",
				"",
				"![gcms SEO 输出真实截图：页面 head 中的 canonical、hreflang、Open Graph 与 sitemap.xml](/assets/screenshots/seo-output.webp)",
				"",
				"## 每一页都是「写好的」HTML",
				"全站服务端渲染，返回给浏览器的是一份完整页面。爬虫无需执行任何 JavaScript，就能拿到标题、正文与结构化数据；首屏内容进入第一个响应包，对 Core Web Vitals 也友好。",
				"",
				"## 该有的标记，一个不缺",
				"- 自指 **canonical**，杜绝重复内容；",
				"- 多语种 **hreflang**（含 `x-default`）；",
				"- **Open Graph** 社交卡片；",
				"- **sitemap.xml** 与分语种 **RSS**；",
				"- `BlogPosting` / `BreadcrumbList` 等 **JSON-LD** 结构化数据，争取搜索结果里的富摘要。",
				"",
				"## 全部自动、且校验通过",
				"以上都按页动态生成，本站每一页都能通过官方富媒体测试。你要做的，只是把文字写好。",
				"",
				"## 发布前还应该检查什么",
				"自动化不等于不用运营。每篇文章仍然建议认真写好 **标题、摘要、Meta 描述、关键词、slug 和封面图 alt**：标题决定点击，描述决定搜索结果里的第一印象，slug 决定地址可读性，封面图决定分享卡片是否可信。gcms 把技术底座铺好，你负责把内容讲清楚。",
			),
		},
		{
			Slug: "seo-by-default", Title: "SEO Shouldn't Be a Post-Launch Chore",
			Excerpt:  "Server rendering, canonical, hreflang, sitemap, RSS and JSON-LD are generated by default. You write; gcms makes it discoverable.",
			MetaDesc: "gcms's built-in SEO: server-side rendering, canonical, multilingual hreflang, sitemap, RSS and JSON-LD structured data — out of the box and validation-clean.",
			Keywords: "SEO,SSR,hreflang,sitemap,structured data,JSON-LD,canonical", Author: "gcms", Cat: "features", Date: "2026-06-08",
			Lang: "en", Group: "s-seo-default", Cover: "/assets/screenshots/seo-output-en.webp",
			Content: md(
				"Many sites treat SEO as homework for after launch. gcms makes it the **default** — you write the content, it handles the rest.",
				"",
				"![Real gcms SEO output screenshot: canonical, hreflang, Open Graph and sitemap.xml](/assets/screenshots/seo-output-en.webp)",
				"",
				"## Every page is already-written HTML",
				"The whole site is server-rendered, returning a complete page. Crawlers get the title, body and structured data without running any JavaScript, and above-the-fold content lands in the first response packet — friendly to Core Web Vitals.",
				"",
				"## Every tag you need, none missing",
				"- Self-referencing **canonical** to kill duplicate content;",
				"- Multilingual **hreflang** (with `x-default`);",
				"- **Open Graph** social cards;",
				"- **sitemap.xml** and per-language **RSS**;",
				"- `BlogPosting` / `BreadcrumbList` **JSON-LD** to earn rich results.",
				"",
				"## All automatic, all validated",
				"Everything is generated per page, and every page here passes the official rich-results test. Your only job is to write well.",
				"",
				"## What to check before publishing",
				"Automation does not replace editorial care. Each post still deserves a clear **title, excerpt, meta description, keywords, slug and image alt text**. The title earns the click, the description shapes the search result, the slug keeps the URL readable, and the cover makes sharing trustworthy. gcms handles the technical base; you make the content convincing.",
			),
		},

		// ===== 6 · 18 套主题（features）=====
		{
			Slug: "eighteen-themes", Title: "内容不变，气质可以随时换",
			Excerpt:  "产品官网、技术博客、交易所推广、AI 教材、外贸工厂、开源项目官网……18 套主题让同一套内容适配不同场景。",
			MetaDesc: "gcms 内置 18 套各具风格的前台主题，后台一键切换，并可按主题微调主色与圆角，无需改一行 CSS。",
			Keywords: "主题,模板,设计,可定制,前端,换肤", Author: "gcms", Cat: "features", Date: "2026-06-07",
			Lang: "zh", Group: "s-themes", Cover: "/assets/screenshots/theme-settings.webp",
			Content: md(
				"同一份内容，能穿上完全不同的「衣服」。gcms 内置 **18 套**布局与气质各异的主题：编辑部、杂志、极客终端、粗野、手账、瑞士、报纸、暗夜、产品官网、交易所、AI 教材、外贸工厂、开源项目官网……",
				"",
				"![gcms 后台外观与主题真实截图：主题卡片、预览缩略图和当前主题选择状态](/assets/screenshots/theme-settings.webp)",
				"",
				"## 一键切换",
				"后台「外观与主题」里点一下即生效，前台立刻换装，内容一字不动。挑主题就像试衣服，不满意随时换回来。",
				"",
				"## 还能微调",
				"每套主题都能单独调**主色**与**圆角**，并把这份偏好存成你自己的风格——不必碰一行 CSS。",
				"",
				"## 主题安全",
				"主题只决定外观，不触碰你的数据；切换、微调都是可逆的设置项。你看到的这身「产品官网」皮肤，就是其中一套。",
				"",
				"## 怎么选主题",
				"如果你做产品官网，优先选信息密度高、CTA 清晰的主题；做技术文档，就选正文宽度克制、代码块舒适的主题；做推广页，可以选更强视觉冲击的主题。主题不是装饰，它决定读者进入内容后的第一判断：这个站是否可信、是否专业、是否值得继续看。",
			),
		},
		{
			Slug: "eighteen-themes", Title: "Same Content, a Different Presence Anytime",
			Excerpt:  "Product site, technical blog, exchange campaign, AI course, garment factory or open-source homepage — 18 themes let one CMS fit many scenes.",
			MetaDesc: "gcms ships 18 distinct front-end themes, switchable from the admin in one click, with per-theme accent and radius tuning — no CSS required.",
			Keywords: "themes,templates,design,customizable,frontend,skins", Author: "gcms", Cat: "features", Date: "2026-06-07",
			Lang: "en", Group: "s-themes", Cover: "/assets/screenshots/theme-settings-en.webp",
			Content: md(
				"The same content can wear completely different clothes. gcms ships **18** themes with distinct layouts and moods: editorial, magazine, terminal, brutalist, notebook, swiss, newspaper, dark pro, product, exchange, academy, garment, open-source, studio…",
				"",
				"![Real gcms Appearance & Themes screenshot: theme cards, preview thumbnails and selected theme state](/assets/screenshots/theme-settings-en.webp)",
				"",
				"## One click",
				"Pick one under Appearance & Themes and it takes effect instantly — the front end re-skins, the content untouched. Trying themes is like trying on clothes; switch back anytime.",
				"",
				"## And fine-tune",
				"Each theme has its own **accent** and **corner radius** you can adjust and save as your own look — without touching a line of CSS.",
				"",
				"## Themes are safe",
				"A theme only decides appearance; it never touches your data. The 'product' skin you're looking at is just one of them.",
				"",
				"## How to choose",
				"For a product site, start with a theme that has clear calls to action and dense but scannable information. For technical docs, choose calm reading width and comfortable code blocks. For a campaign page, pick a bolder visual system. A theme is not decoration; it decides whether the visitor reads the site as credible and worth continuing.",
			),
		},

		// ===== 7 · 自动化与 API（ops）=====
		{
			Slug: "automation-api", Title: "把重复运营交给自动化",
			Excerpt:  "开放文章、页面和链接的安全接口，配好权限、OpenAPI 和 AI 使用包。脚本负责重复动作，人负责判断边界。",
			MetaDesc: "gcms 的自动化接口：带权限范围的 API 密钥、OpenAPI 描述、调用日志与可导出的 AI 技能包，让脚本、定时任务与 AI 助手安全地发布与管理内容。",
			Keywords: "API,自动化,OpenAPI,AI,密钥,集成", Author: "gcms", Cat: "ops", Date: "2026-06-06",
			Lang: "zh", Group: "s-automation", Cover: "/assets/screenshots/automation-api.webp",
			Content: md(
				"内容运营里有很多重复动作：同步链接、生成草稿、补 SEO 描述、批量更新页面。gcms 把「语种、分类读取」和「文章、页面、链接」开放成一组受控接口，让自动化帮你做这些琐事。",
				"",
				"![gcms 自动化接口真实截图：文章、链接、页面能力说明，访问权限列表和接入方式](/assets/screenshots/automation-api.webp)",
				"",
				"## 带权限的 API 密钥",
				"在后台签发密钥，按文章、页面、链接分组授权，可随时吊销、可查最近使用时间。密钥只在创建时完整显示一次，存的是哈希——丢了就吊销重发，不怕泄露。",
				"",
				"## 标准化描述",
				"自带 **OpenAPI** 描述与调用日志，接入任何 HTTP 客户端、Webhook 或自动化平台都很直接。每一次写入都有迹可循。",
				"",
				"## 给 AI 的技能包",
				"还能导出一份「技能包」，把站点的发布能力描述给 AI 助手——让它按你的规则产出草稿、补全 SEO、安排发布。",
				"",
				"## 不调用 AI API 也能接入",
				"gcms 不替你调用大模型 API。它提供的是**开放文档、OpenAPI 描述和助手使用包**：你把这些文件交给 Codex、Cursor、Claude、ChatGPT 或自动化工具，它们就能按 HTTP 接口操作站点。这样源码仓库可以私有，站点密钥也可随时吊销，边界更清楚。",
				"",
				"## 权限边界",
				"默认只开放语种、分类读取和文章、页面、链接内容操作，不开放主题、安全、用户和系统设置，也不开放分类增删改。一个密钥只给一个工具或一个任务使用；不用了就吊销，怀疑泄露就删除并重新生成。",
				"",
				"> 把重复劳动交给自动化，把判断留给你自己。",
			),
		},
		{
			Slug: "automation-api", Title: "Hand Repetitive Ops to Automation",
			Excerpt:  "Expose posts, pages and links through safe APIs, scoped keys, OpenAPI and an AI package. Scripts repeat; humans decide.",
			MetaDesc: "gcms's automation layer: scoped API keys, an OpenAPI description, call logs and an exportable AI skill package, so scripts, cron jobs and AI assistants can publish and manage content safely.",
			Keywords: "API,automation,OpenAPI,AI,keys,integration", Author: "gcms", Cat: "ops", Date: "2026-06-06",
			Lang: "en", Group: "s-automation", Cover: "/assets/screenshots/automation-api-en.webp",
			Content: md(
				"Content operations have repetitive work: syncing links, drafting posts, filling SEO descriptions, updating pages in batches. gcms exposes language and category reads plus posts, pages and links through controlled APIs so automation can handle the chores.",
				"",
				"![Real gcms automation API screenshot: capabilities for posts, links, pages, access keys and integration files](/assets/screenshots/automation-api-en.webp)",
				"",
				"## Scoped API keys",
				"Issue keys from the admin, grant scopes by posts, pages and links, revoke anytime, and see when each was last used. A key is shown in full once at creation; only its hash is stored — lost one? Revoke and reissue.",
				"",
				"## A standard description",
				"It ships an **OpenAPI** description and call logs, so wiring up any HTTP client, webhook or automation platform is straightforward — and every write is traceable.",
				"",
				"## A skill package for AI",
				"Export a 'skill package' that describes the site's publishing capabilities to an AI assistant — so it can draft, fill in SEO and schedule posts by your rules.",
				"",
				"## No AI API required",
				"gcms does not call an AI model for you. It provides **public docs, an OpenAPI description and an assistant package**. Give those files to Codex, Cursor, Claude, ChatGPT or an automation tool, and they can operate the site over HTTP. Your source repo stays private, and a site key can be revoked whenever the boundary changes.",
				"",
				"## Permission boundary",
				"Only languages, category reads, and content operations for posts, pages and links are exposed by default — not themes, security, users, system settings, or category writes. Use one key for one tool or one workflow; revoke what you stop using, and regenerate anything you suspect has leaked.",
				"",
				"> Hand the repetitive work to automation; keep the judgment yourself.",
			),
		},

		// ===== 8 · AI 内容助手 Skill（ops）=====
		{
			Slug: "gcms-content-assistant-skill", Title: "让 AI 成为内容运营助手：gcms Skill 使用指南",
			Excerpt:  "从后台下载专属 AI 接入包，交给 Codex、Claude Code 或 Cursor，让 AI 按权限诊断、巡检、写草稿、补 SEO 和上传图片。",
			MetaDesc: "gcms Content Assistant Skill 使用指南：在后台自动化接口创建访问权限、下载 AI 接入包、安装到 AI 工具、运行 doctor 检查，并用标准任务提示完成内容运营。",
			Keywords: "gcms,Skill,AI助手,内容运营,自动化接口,OpenAPI,安装", Author: "gcms", Cat: "ops", Date: "2026-06-15",
			Lang: "zh", Group: "s-content-assistant-skill", Featured: true, Cover: "/assets/screenshots/automation-api.webp",
			Content: md(
				"如果说自动化接口解决的是「AI 能不能安全访问网站」，那么 **gcms Content Assistant Skill** 解决的是下一步：AI 到底该按什么规则工作。",
				"",
				"它不是一个在线服务，也不是 gcms 主动调用的大模型 API。它是一份可以下载的接入包，里面包含权限专用密钥、OpenAPI 描述、AI 使用说明、Skill 文件和一个命令行脚本。你把它交给 AI 工具，AI 就能按你的权限边界处理文章、页面、链接和媒体。",
				"",
				"![gcms 后台自动化接口真实截图：创建访问权限、下载 AI 接入包和查看接口说明](/assets/screenshots/automation-api.webp)",
				"",
				"## 先准备 gcms 本体",
				"如果你还没有运行 gcms，先从发布仓库下载正式包：",
				"",
				"- 下载发布包：[GitHub Releases](https://github.com/ccvar/gcms-releases/releases/latest)；",
				"- 一键安装：`curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`；",
				"- 本地启动后进入 `/admin`，先修改默认后台密码。",
				"",
				"Skill 不是单独安装到服务器上的插件。它是给外部 AI 工具使用的，所以要先有一个已经能访问的 gcms 站点，再给 AI 创建受限访问权限。",
				"",
				"## 在哪里下载 Skill",
				"进入后台「设置 → 自动化接口」，点击「创建访问权限」。给它起一个清楚的名字，例如「内容运营助手」或「SEO 草稿助手」，然后勾选需要的能力。",
				"",
				"创建成功后，页面会显示一次访问密钥，并提供「下载 AI 接入包」。这就是最推荐的下载入口，因为包里已经写好当前站点的 `GCMS_API_BASE` 和这一条权限对应的 `GCMS_API_KEY`。",
				"",
				"如果你只是开发或本地调试，也可以参考源码里的 `skills/gcms-content-assistant` 模板；但正式使用时，仍然建议从自己的后台下载专属包。密钥和权限属于你的站点，不应该从公共仓库复制。",
				"",
				"## 怎么安装到 AI 工具",
				"下载后解压，你会看到一个 `gcms-content-assistant` 文件夹。安装方式取决于你使用的工具：",
				"",
				"- **Codex / Claude Code / Cursor**：把整个文件夹交给工具读取，或在项目中打开这个文件夹；",
				"- **支持 Skills 的工具**：把 `gcms-content-assistant` 作为一个 Skill 目录导入或放进该工具的 skills 目录；",
				"- **不支持 Skills 的工具**：让它读取 `SKILL.md`、`AI助手说明.md` 和 `references/openapi.json`，再按文档调用 HTTP 接口；",
				"- **只想写脚本**：直接使用 `scripts/gcms.js`，它会读取 `.env` 里的 `GCMS_API_BASE` 和 `GCMS_API_KEY`。",
				"",
				"第一次接入后，先在 `gcms-content-assistant` 目录运行：",
				"",
				"~~~bash",
				"node scripts/gcms.js doctor",
				"~~~",
				"",
				"`doctor` 会检查接口地址、密钥、OpenAPI、语种、文章分类、链接分类和媒体上传权限。这个检查通过后，再让 AI 写内容，会少很多来回排错。",
				"",
				"## 它适合做什么",
				"这个 Skill 适合承担内容运营里的重复和整理工作：",
				"",
				"- 检查最近一批文章是否缺标题、摘要、SEO 描述、关键词、分类或封面图；",
				"- 根据资料创建文章草稿，并自动查询 `category_id`；",
				"- 上传封面图或正文图片，把返回 URL 写入 `cover_image` 或 Markdown 图片；",
				"- 维护链接资源，补充介绍、摘要、SEO 字段和分类；",
				"- 按 `trans_group` 找到多语种版本，分别优化各语种标题和描述；",
				"- 发布前复核草稿是否具备上线条件。",
				"",
				"它不应该默认发布内容，也不应该改站点设置、主题、安全、导航和分类结构。这些仍然由后台人工操作更稳。",
				"",
				"## 给 AI 的任务要怎么说",
				"不要只说「帮我优化一下网站」。更好的说法是把范围、对象、动作、边界和输出讲清楚：",
				"",
				"~~~text",
				"先运行 doctor 检查连接和权限。",
				"检查最近 50 篇中文文章，重点看标题、摘要、SEO 描述、关键词、分类和封面图。",
				"只输出问题列表和建议，不要修改内容。",
				"如果发现多个相似标题，先列出 ID 让我确认。",
				"最后按优先级给我一个表格：id、标题、问题、建议动作。",
				"~~~",
				"",
				"创建内容时也一样明确：先查分类、保持草稿、上传图片后写入封面、完成后回读确认字段。AI 越清楚边界，越像一个可靠的运营助理。",
				"",
				"## 权限建议",
				"刚开始只给 `languages:read`、分类读取、内容读取和草稿写入。等你确认流程稳定后，再考虑给某个专用助手增加发布权限。发布权限最好单独创建一条密钥，不要和日常巡检助手混在一起。",
				"",
				"如果密钥泄露、任务结束或工具不用了，直接回到后台吊销对应访问权限。gcms 会记录最近使用时间，方便你判断哪些权限已经闲置。",
				"",
				"> 好的 Skill 不是让 AI 无所不能，而是让它在清楚的边界里稳定做事。",
			),
		},
		{
			Slug: "gcms-content-assistant-skill", Title: "Turn AI into a Content Ops Assistant with the gcms Skill",
			Excerpt:  "Download a dedicated AI package from the admin, give it to Codex, Claude Code or Cursor, and let AI diagnose, audit, draft, improve SEO and upload media within scoped permissions.",
			MetaDesc: "A practical guide to the gcms Content Assistant Skill: create an automation key, download the AI package, install it in an AI tool, run doctor, and use standard task prompts for content operations.",
			Keywords: "gcms,Skill,AI assistant,content operations,automation API,OpenAPI,install", Author: "gcms", Cat: "ops", Date: "2026-06-15",
			Lang: "en", Group: "s-content-assistant-skill", Featured: true, Cover: "/assets/screenshots/automation-api-en.webp",
			Content: md(
				"If the automation API answers whether AI can access your site safely, the **gcms Content Assistant Skill** answers the next question: how should AI work once it has access?",
				"",
				"It is not an online service, and gcms does not call an AI model for you. It is a downloadable integration package containing a scoped key, OpenAPI description, assistant instructions, a Skill file and a small CLI helper. Give it to an AI tool, and the tool can operate posts, pages, links and media within the boundary you grant.",
				"",
				"![Real gcms Automation API screenshot: create access keys, download AI package and inspect API documentation](/assets/screenshots/automation-api-en.webp)",
				"",
				"## Prepare gcms first",
				"If you do not have gcms running yet, start with the release package:",
				"",
				"- Download packages: [GitHub Releases](https://github.com/ccvar/gcms-releases/releases/latest);",
				"- One-line install: `curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`;",
				"- Open `/admin` after launch and change the default admin password first.",
				"",
				"The Skill is not a server-side plugin. It is for external AI tools, so you need a reachable gcms site before creating a scoped access key for AI.",
				"",
				"## Where to download the Skill",
				"Open Settings → Automation API in the admin, then create an access key. Give it a clear name such as Content Assistant or SEO Draft Assistant, and grant only the scopes it needs.",
				"",
				"After creation, the page shows the key once and offers Download AI Package. That is the recommended download path because the package already contains the correct `GCMS_API_BASE` and the `GCMS_API_KEY` for that specific access rule.",
				"",
				"For development or local testing, you can also inspect the `skills/gcms-content-assistant` template in the source tree. For real use, download a dedicated package from your own admin. Keys and scopes belong to your site; they should not come from a public repository.",
				"",
				"## How to install it in an AI tool",
				"After downloading, unzip the package. You will get a `gcms-content-assistant` folder. Installation depends on the tool:",
				"",
				"- **Codex / Claude Code / Cursor**: open or attach the whole folder so the tool can read it;",
				"- **Tools with Skill support**: import `gcms-content-assistant` as a Skill directory or place it in that tool's skills folder;",
				"- **Tools without Skills**: ask the tool to read `SKILL.md`, `AI助手说明.md` and `references/openapi.json`, then call the HTTP API described there;",
				"- **Scripts only**: use `scripts/gcms.js`; it reads `GCMS_API_BASE` and `GCMS_API_KEY` from `.env`.",
				"",
				"On first connection, run this inside the `gcms-content-assistant` folder:",
				"",
				"~~~bash",
				"node scripts/gcms.js doctor",
				"~~~",
				"",
				"`doctor` checks the API base, key, OpenAPI, languages, post categories, link categories and media upload permission. Passing this check before writing content saves a lot of back-and-forth debugging.",
				"",
				"## What it is good at",
				"This Skill is designed for repetitive and structured content operations:",
				"",
				"- Audit recent posts for missing titles, excerpts, SEO descriptions, keywords, categories or cover images;",
				"- Create post drafts from source material and choose a valid `category_id`;",
				"- Upload cover or inline images and write returned URLs into `cover_image` or Markdown image syntax;",
				"- Maintain link resources with descriptions, excerpts, SEO fields and categories;",
				"- Find multilingual versions by `trans_group` and improve each language separately;",
				"- Review whether a draft is ready to publish.",
				"",
				"It should not publish by default, nor should it modify site settings, themes, security, navigation or category structure. Those remain safer as deliberate admin actions.",
				"",
				"## How to ask AI for work",
				"Do not just say: improve my site. State the range, target, action, boundary and output format:",
				"",
				"~~~text",
				"Run doctor first to check the connection and permissions.",
				"Audit the latest 50 Chinese posts for missing title, excerpt, SEO description, keywords, category and cover image.",
				"Only return issues and suggestions; do not modify content.",
				"If multiple similar titles appear, list their IDs and ask me to confirm.",
				"Return a table with id, title, issue and recommended action.",
				"~~~",
				"",
				"The same applies to creating content: query categories first, keep status as draft, upload images before writing cover URLs, and read the item back after updating. The clearer the boundary, the more reliable the assistant becomes.",
				"",
				"## Permission advice",
				"Start with `languages:read`, category reads, content reads and draft writes. After the workflow feels stable, consider granting publish permission to a separate dedicated assistant. Do not mix publishing with a daily audit key.",
				"",
				"If a key leaks, a project ends, or a tool is no longer used, revoke that access rule in the admin. gcms records recent use, so stale keys are easy to spot.",
				"",
				"> A good Skill does not make AI all-powerful. It makes AI reliable inside a clear boundary.",
			),
		},

		// ===== 9 · 后台在线更新（ops）=====
		{
			Slug: "in-app-updates", Title: "自托管，也能像 App 一样升级",
			Excerpt:  "后台检测新版本，下载对应平台包，校验 SHA256，替换并重启。源码仓库可以私有，用户只接触公开发布包。",
			MetaDesc: "gcms 的在线更新：后台比对公开发布仓库的 manifest 检查新版本，一键下载对应平台包、校验 SHA256、替换并重启，自托管也能像用 App 一样省心。",
			Keywords: "更新,升级,自托管,manifest,校验和,运维", Author: "gcms", Cat: "ops", Date: "2026-06-05",
			Lang: "zh", Group: "s-updates", Cover: "/assets/screenshots/system-updates.webp",
			Content: md(
				"自托管最怕「装好就没人管」。gcms 把升级也做进了后台，让维护这件事不再需要你登服务器敲命令。",
				"",
				"![gcms 系统更新真实截图：当前版本、最新版本、升级任务状态和后台升级按钮](/assets/screenshots/system-updates.webp)",
				"",
				"## 自动检查",
				"后台「系统更新」会比对公开发布仓库的清单（`manifest.json`），告诉你**有没有新版本、更新了什么**。源码仓库可以私有，发布仓库公开，互不影响。",
				"",
				"## 一键升级",
				"确认后，自动下载对应平台的包、**校验 SHA256**、替换二进制并重启——全程在浏览器里完成。校验和保证下载完整，绝不会装上半个文件。",
				"",
				"## 始终可控",
				"发布仓库公开可查，你随时知道升级到的是哪个版本、来自哪次发布。要稳妥，也可以继续用发布包手动替换——在线更新只是更省心的那条路。",
				"",
				"## 升级前建议",
				"升级前建议确认两件事：第一，数据库文件已经备份；第二，当前运行目录是标准发布目录。这样即使升级中断，也能用旧二进制和数据库备份快速回到上一版。gcms 的升级目标不是炫技，而是把自托管维护变成一个可预期的日常动作。",
				"",
				"> 自托管，也可以像用 App 一样省心。",
			),
		},
		{
			Slug: "in-app-updates", Title: "Self-Hosted, Upgraded Like an App",
			Excerpt:  "The admin checks for a new version, downloads the right package, verifies SHA256, swaps and restarts. Source can stay private; users get public releases.",
			MetaDesc: "gcms in-app updates: the admin checks a public release manifest for new versions, then downloads the right platform package, verifies SHA256, replaces the binary and restarts — self-hosting as easy as using an app.",
			Keywords: "updates,upgrade,self-hosted,manifest,checksum,ops", Author: "gcms", Cat: "ops", Date: "2026-06-05",
			Lang: "en", Group: "s-updates", Cover: "/assets/screenshots/system-updates-en.webp",
			Content: md(
				"The danger of self-hosting is the 'install it and forget it' trap. gcms builds upgrading into the admin, so maintenance no longer means SSH-ing in to run commands.",
				"",
				"![Real gcms system update screenshot: current version, latest version, upgrade task status and in-app update button](/assets/screenshots/system-updates-en.webp)",
				"",
				"## Automatic checks",
				"Settings → System Updates compares a public release manifest (`manifest.json`) and tells you **whether there's a new version and what changed**. Your source repo can stay private while the release repo is public — independent of each other.",
				"",
				"## One-click upgrade",
				"Confirm, and it downloads the right platform package, **verifies the SHA256**, replaces the binary and restarts — all in the browser. The checksum guarantees a complete download; you'll never install half a file.",
				"",
				"## Always in control",
				"The release repo is public and auditable, so you always know which version you upgraded to and from which release. Prefer caution? Keep replacing packages by hand — in-app update is just the easier path.",
				"",
				"## Before you upgrade",
				"Check two things first: your database file is backed up, and the current runtime directory follows the standard release layout. Then even if an upgrade is interrupted, you can return to the previous version with the old binary and database backup. The goal is not magic; it is predictable maintenance.",
				"",
				"> Self-hosting can be as low-maintenance as using an app.",
			),
		},

		// ===== 10 · 实用教程：更换主题（guides）=====
		{
			Slug: "how-to-change-theme", Title: "怎么更改网站主题？从预览到上线的完整步骤",
			Excerpt:  "不用改 CSS，也不用重新部署。进入外观与主题，预览、选择、微调主色和圆角，保存后前台立即生效。",
			MetaDesc: "gcms 更换网站主题教程：在后台外观与主题页面预览 18 套主题，选择适合场景的风格，微调主色与圆角，并保存到正式前台。",
			Keywords: "gcms,更改主题,外观设置,主题预览,网站设计", Author: "gcms", Cat: "guides", Date: "2026-06-14",
			Lang: "zh", Group: "g-change-theme", Featured: true, Cover: "/assets/screenshots/theme-settings.webp",
			Content: md(
				"主题决定读者第一次进入网站时的感受：它像不像一个正式产品、读起来是否舒服、按钮是否明确。gcms 的主题切换是后台设置项，不需要改代码，也不需要重新部署。",
				"",
				"![gcms 后台外观与主题页面真实截图：主题卡片、预览缩略图和当前主题选择状态](/assets/screenshots/theme-settings.webp)",
				"",
				"## 第一步：进入外观与主题",
				"登录后台，打开「设置 → 外观与主题」。页面上会列出内置主题，每张卡片都是当前内容在该主题下的真实预览，不是静态占位图。",
				"",
				"## 第二步：按场景选主题",
				"产品官网优先看首页首屏是否清楚、CTA 是否醒目；技术文档优先看正文宽度、代码块和目录；活动推广页可以选择视觉更强的主题。不要只看好不好看，要看它是否适合你的内容。",
				"",
				"## 第三步：微调主色和圆角",
				"选中主题后，可以打开自定义设置，调整主色和圆角。主色建议和品牌色保持一致；圆角则影响整体气质：小圆角更偏工具与文档，大圆角更偏柔和和营销。",
				"",
				"## 第四步：保存并检查前台",
				"点击保存后，前台立即生效。建议检查首页、文章页、分类页和链接页四个位置，确认标题、按钮、代码块、图片和导航都协调。",
				"",
				"> 主题不是装饰，它是内容被信任之前的第一层判断。",
			),
		},
		{
			Slug: "how-to-change-theme", Title: "How to Change the Site Theme",
			Excerpt:  "No CSS and no redeploy. Open Appearance & Themes, preview, choose, tune accent color and radius, then save.",
			MetaDesc: "A practical gcms guide to changing the front-end theme: preview 18 themes in the admin, choose the right style, tune accent color and radius, and publish it instantly.",
			Keywords: "gcms,change theme,appearance,theme preview,website design", Author: "gcms", Cat: "guides", Date: "2026-06-14",
			Lang: "en", Group: "g-change-theme", Featured: true, Cover: "/assets/screenshots/theme-settings-en.webp",
			Content: md(
				"A theme shapes the first impression: whether the site feels like a real product, whether it is comfortable to read, and whether calls to action are clear. In gcms, switching themes is an admin setting, not a code change.",
				"",
				"![Real gcms admin screenshot: Appearance & Themes with theme cards, live previews and the selected theme](/assets/screenshots/theme-settings-en.webp)",
				"",
				"## Step 1: Open Appearance & Themes",
				"Log in to the admin and go to Settings → Appearance & Themes. Each card previews your current content in that theme, so you are not choosing from placeholder art.",
				"",
				"## Step 2: Choose by use case",
				"For a product site, check whether the hero and CTA are clear. For docs, inspect reading width, code blocks and navigation. For campaign pages, a stronger visual theme may be right. Do not choose only by taste; choose by content fit.",
				"",
				"## Step 3: Tune accent and radius",
				"After selecting a theme, enable custom settings and adjust accent color and corner radius. Match the accent to your brand; use smaller radius for tool-like sites and larger radius for softer marketing pages.",
				"",
				"## Step 4: Save and verify the front end",
				"After saving, the front end updates immediately. Check the homepage, article page, category page and links page to make sure headings, buttons, code blocks, images and navigation still feel coherent.",
				"",
				"> A theme is not decoration. It is the first layer of trust before the content is read.",
			),
		},

		// ===== 11 · 实用教程：AI 运营（guides）=====
		{
			Slug: "how-to-ai-content-ops", Title: "怎么把网站内容交给 AI 运营？",
			Excerpt:  "gcms 不直接调用 AI API，而是给 AI 工具一份受限接口：密钥、OpenAPI、助手说明和可写范围都由你控制。",
			MetaDesc: "用 gcms 自动化接口让 AI 工具参与网站内容运营：创建访问权限、下载 AI 接入包、限制文章页面链接权限，并保持人工审核边界。",
			Keywords: "gcms,AI运营,自动化接口,OpenAPI,API Key,内容运营", Author: "gcms", Cat: "guides", Date: "2026-06-14",
			Lang: "zh", Group: "g-ai-content-ops", Featured: true, Cover: "/assets/screenshots/automation-api.webp",
			Content: md(
				"让 AI 参与内容运营，不等于把后台账号交出去。gcms 的做法是开放一组受限接口，只让外部工具访问文章、页面和链接，并且每个工具单独一条访问权限。",
				"",
				"![gcms 后台自动化接口真实截图：文章、链接、页面能力说明，访问权限列表和接入方式](/assets/screenshots/automation-api.webp)",
				"",
				"## 第一步：创建一条专用访问权限",
				"进入「设置 → 自动化接口」，点击「创建访问权限」。建议一个 AI 工具创建一条，例如「内容运营助手」或「SEO 草稿助手」。以后不用了，直接吊销这一条即可。",
				"",
				"## 第二步：只给必要权限",
				"默认建议给「读取、写草稿」权限，不要一开始就给发布权限。让 AI 先创建草稿、补标题、摘要、关键词和正文结构，最后仍由人在后台审核发布。",
				"",
				"## 第三步：下载 AI 接入包",
				"密钥只完整显示一次。创建成功后，下载专属 AI 接入包，里面包含 OpenAPI 描述、环境变量示例、助手说明和调用脚本。把这份包交给 Codex、Claude Code、Cursor 或其他支持工具读取。",
				"",
				"## 第四步：给 AI 明确任务边界",
				"你可以这样描述任务：先查询文章列表，找到目标文章 ID；只修改草稿；补充 SEO 描述；不要删除内容；发布前把修改摘要发给我确认。真正重要的不是让 AI 能做什么，而是规定它不能做什么。",
				"",
				"## 第五步：定期清理访问权限",
				"每个密钥只服务一个工具或流程。项目结束、成员离开、密钥疑似泄露时，直接吊销。gcms 会记录最近使用时间，方便判断哪些权限已经不用了。",
				"",
				"> AI 适合做重复、整理和草稿工作；最终判断仍然应该留在人手里。",
			),
		},
		{
			Slug: "how-to-ai-content-ops", Title: "How to Let AI Help Operate Your Content",
			Excerpt:  "gcms does not call an AI API itself. It gives AI tools a controlled interface: key, OpenAPI, assistant guide and scoped write access.",
			MetaDesc: "Use gcms automation APIs to let AI tools assist content operations: create scoped keys, download the AI package, limit access to posts pages and links, and keep human review in the loop.",
			Keywords: "gcms,AI content ops,automation API,OpenAPI,API key,content operations", Author: "gcms", Cat: "guides", Date: "2026-06-14",
			Lang: "en", Group: "g-ai-content-ops", Featured: true, Cover: "/assets/screenshots/automation-api-en.webp",
			Content: md(
				"Letting AI help with content operations does not mean handing over your admin account. gcms exposes a limited interface for posts, pages and links, and each external tool gets its own access key.",
				"",
				"![Real gcms admin screenshot: automation API capabilities, access key list and integration options](/assets/screenshots/automation-api-en.webp)",
				"",
				"## Step 1: Create one key per tool",
				"Go to Settings → Automation API and create an access key. Use a clear name, such as Content Assistant or SEO Draft Assistant. If you stop using that tool, revoke only that key.",
				"",
				"## Step 2: Grant only necessary scopes",
				"Start with read and draft-write access. Do not grant publish permission by default. Let AI create drafts, improve titles, excerpts, keywords and structure; keep final review and publish in the admin.",
				"",
				"## Step 3: Download the AI package",
				"The full key is shown once. After creating it, download the dedicated AI package. It includes OpenAPI, env examples, assistant instructions and a helper script. Give that package to Codex, Claude Code, Cursor or another compatible tool.",
				"",
				"## Step 4: State the boundaries",
				"A good instruction is explicit: list posts first, find the target ID, only edit drafts, improve SEO descriptions, never delete content, and summarize changes for review before publishing. The important part is not only what AI can do, but what it must not do.",
				"",
				"## Step 5: Clean up access regularly",
				"One key should serve one tool or workflow. Revoke it when a project ends, a member leaves, or you suspect exposure. gcms records recent use so stale keys are easy to spot.",
				"",
				"> AI is good at repetition, organization and drafts. Judgment should stay with people.",
			),
		},

		// ===== 12 · 实用教程：可视化编辑（guides）=====
		{
			Slug: "visual-edit-homepage-copy", Title: "怎么直接在首页预览里修改站点文案？",
			Excerpt:  "打开可视化编辑，在真实前台页面上点选站点名称、Hero 文案、导航和页脚，右侧面板实时编辑并保存。",
			MetaDesc: "gcms 可视化编辑教程：在真实前台预览中直接修改站点名称、首页 Hero、导航文案、分类入口和页脚信息，并按语种保存。",
			Keywords: "gcms,可视化编辑,首页文案,站点设置,多语种", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "zh", Group: "g-visual-edit", Cover: "/assets/screenshots/visual-editor-home.webp",
			Content: md(
				"很多普通用户不知道「站点名称」「标语」「首页标题」到底会显示在哪里。可视化编辑解决的就是这个问题：打开真实前台页面，在看到的位置直接改。",
				"",
				"![gcms 可视化编辑真实截图：左侧真实前台预览、可点击虚线框和右侧编辑分组](/assets/screenshots/visual-editor-home.webp)",
				"",
				"## 第一步：进入可视化编辑",
				"后台顶部点击「可视化编辑」。页面左侧是真实前台预览，右侧是可编辑内容分组。虚线框代表当前页面可点选的内容。",
				"",
				"## 第二步：选择语种",
				"顶部可以切换中文和 English。你正在编辑哪个语种，保存时就只影响哪个语种；未填写的内容会回落默认语种。",
				"",
				"## 第三步：点击页面上的文字",
				"例如点击 Hero 标题、说明文字、按钮、导航名称或页脚说明，右侧就会展开对应表单。修改后保存，左侧预览会同步更新。",
				"",
				"## 第四步：用浏览模式检查跳转",
				"编辑模式用于改文字，浏览模式用于在预览里正常跳转。改完首页后，建议切换浏览模式，点一遍导航和按钮，确认链接路径正确。",
				"",
				"## 什么时候用它",
				"可视化编辑最适合改站点基础文案、首页内容、导航名称、分类入口说明和页脚。文章正文仍建议在文章编辑器里写，这样标题、封面、SEO 和正文能一起维护。",
			),
		},
		{
			Slug: "visual-edit-homepage-copy", Title: "How to Edit Homepage Copy Visually",
			Excerpt:  "Open Visual Editing, click real homepage content, then edit site name, hero copy, navigation and footer from the side panel.",
			MetaDesc: "A gcms visual editing guide: edit site name, homepage hero, navigation labels, category entries and footer copy directly from the live front-end preview, per language.",
			Keywords: "gcms,visual editing,homepage copy,site settings,multilingual", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "en", Group: "g-visual-edit", Cover: "/assets/screenshots/visual-editor-home-en.webp",
			Content: md(
				"Many non-technical users do not know where site name, tagline or hero title will appear. Visual Editing solves that by letting you edit directly on the real front-end preview.",
				"",
				"![Real gcms screenshot: visual editor with live front-end preview, editable dashed outlines and grouped controls](/assets/screenshots/visual-editor-home-en.webp)",
				"",
				"## Step 1: Open Visual Editing",
				"Click Visual Editing in the admin header. The left side is the real front-end preview; the right side lists editable groups. Dashed outlines mark content you can click.",
				"",
				"## Step 2: Choose a language",
				"Switch between Chinese and English at the top. Edits apply only to the current language; empty values fall back to the default language.",
				"",
				"## Step 3: Click visible copy",
				"Click the hero title, description, buttons, navigation labels or footer copy. The matching form opens on the right. Save, and the preview updates.",
				"",
				"## Step 4: Check links in browse mode",
				"Edit mode changes text; browse mode lets you navigate inside the preview. After changing the homepage, switch to browse mode and click navigation and buttons to confirm paths.",
				"",
				"## When to use it",
				"Visual Editing is best for site basics, homepage copy, navigation labels, category entry text and footer copy. Use the article editor for post content so title, cover, SEO and body stay together.",
			),
		},

		// ===== 13 · 实用教程：导航与分类（guides）=====
		{
			Slug: "configure-navigation-and-categories", Title: "怎么配置导航菜单和分类入口？",
			Excerpt:  "导航负责把人带到哪里，分类负责让内容如何分组。先看预览，再选择常用入口，必要时自定义路径。",
			MetaDesc: "gcms 导航和分类配置教程：用导航预览确认最终菜单，选择首页、分类、链接、页面等常用入口，配置多语种菜单文字和分类入口 slug。",
			Keywords: "gcms,导航菜单,分类入口,Slug,多语种导航", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "zh", Group: "g-navigation", Cover: "/assets/screenshots/navigation-menu.webp",
			Content: md(
				"一个内容站最常见的混乱，不是文章不够多，而是读者不知道下一步该点哪里。gcms 把导航和分类入口放在同一个站点配置体系里：先看最终预览，再配置每一项。",
				"",
				"![gcms 导航菜单真实截图：导航预览、常用入口下拉、自定义路径和菜单文字配置](/assets/screenshots/navigation-menu.webp)",
				"",
				"## 导航菜单：决定顶部能去哪里",
				"进入「设置 → 站点配置 → 导航菜单」。上方的导航预览会按当前顺序实时更新。你可以选择首页、文章分类页、链接页、页面，也可以选择自定义站内路径或外部链接。",
				"",
				"## 菜单文字：按语种分别命名",
				"如果启用了中文和英文，同一个导航项可以分别填写中文和 English。路径是全站共用的，菜单文字按语种显示。",
				"",
				"## 拖动排序：先把最重要的放前面",
				"左侧手柄可以拖动排序。产品官网建议顺序是：首页、功能或指南、资源、开始使用；文档站可以把指南或文档放得更靠前。",
				"",
				"## 分类入口：决定列表页怎么命名",
				"进入「分类入口」可以设置文章分类页和链接分类页的全部入口，包括标题、说明、按钮文字和 slug。导航里的「分类」应该指向这个全部入口，而不是某一个单独分类。",
				"",
				"## 一个实用建议",
				"导航不要塞太满。顶部导航只放读者最常用的 4 到 6 个入口，更多内容交给页脚、文章内链接和资源页承接。",
			),
		},
		{
			Slug: "configure-navigation-and-categories", Title: "How to Configure Navigation and Category Entrances",
			Excerpt:  "Navigation decides where people go; categories decide how content is grouped. Preview first, pick common entries, then customize paths when needed.",
			MetaDesc: "A gcms guide to navigation and category setup: preview the final menu, choose common entries such as home categories links and pages, edit multilingual labels and category slugs.",
			Keywords: "gcms,navigation menu,category entrance,slug,multilingual navigation", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "en", Group: "g-navigation", Cover: "/assets/screenshots/navigation-menu-en.webp",
			Content: md(
				"A content site usually becomes confusing not because it lacks articles, but because readers do not know where to go next. gcms keeps navigation and category entrances in one site-configuration flow: preview first, then configure.",
				"",
				"![Real gcms screenshot: navigation preview, common-entry dropdown, custom path and menu labels](/assets/screenshots/navigation-menu-en.webp)",
				"",
				"## Navigation decides the top-level paths",
				"Go to Settings → Site Configuration → Navigation Menu. The preview updates in the order you set. Choose home, article categories, links, pages, custom internal paths or external links.",
				"",
				"## Menu text is per language",
				"If Chinese and English are enabled, the same item can have separate labels per language. The path is shared; the label changes by locale.",
				"",
				"## Drag important items forward",
				"Use the left handle to reorder. A product site usually works well with Home, Features or Guides, Resources and Get Started. A docs site may place Guides or Docs earlier.",
				"",
				"## Category entrances name the list pages",
				"Category Entrance lets you configure the all-posts and all-links pages: title, description, button label and slug. The main navigation category item should point to this all-category entrance, not to a single category.",
				"",
				"## A practical rule",
				"Do not overload the top navigation. Keep 4 to 6 high-frequency entries there, and let the footer, article links and resource pages carry the rest.",
			),
		},

		// ===== 14 · 实用教程：首装安全与演示数据（guides）=====
		{
			Slug: "first-launch-security-and-demo-data", Title: "首次上线后，先做这两件事",
			Excerpt:  "改掉默认后台密码，再决定是保留产品演示站继续改，还是只清除演示数据从空站开始。",
			MetaDesc: "gcms 首次上线安全教程：修改默认后台密码，理解重新载入产品演示站与只清除演示数据的区别，避免正式站带着默认内容上线。",
			Keywords: "gcms,首次上线,默认密码,演示数据,安全设置", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "zh", Group: "g-first-launch-security", Cover: "/assets/screenshots/security-demo-data.webp",
			Content: md(
				"gcms 首次启动会写入产品演示站，方便你看到完整效果。但真正上线前，第一件事不是写文章，而是先把安全和演示数据处理干净。",
				"",
				"![gcms 安全设置真实截图：修改后台密码、重新载入产品演示站和只清除演示数据](/assets/screenshots/security-demo-data.webp)",
				"",
				"## 第一件事：修改默认密码",
				"默认账号用于首装体验，不能留到正式上线。进入「设置 → 安全」，输入当前密码和新密码。新密码至少 6 位，保存后重新登录确认生效。",
				"",
				"## 第二件事：决定演示数据怎么处理",
				"如果你想基于 gcms 产品演示站改造成自己的官网，点击「重新载入产品演示站」，它会恢复最新样板内容。随后你可以替换站点名称、导航、文章、链接和页面。",
				"",
				"如果你已经准备好自己的内容，点击「只清除演示数据」。它会删除内置文章、页面、链接、分类和示例导航，但不会删除管理员账号、密码、Logo、上传文件、主题和基础配置。",
				"",
				"## 正式上线前的检查清单",
				"- 后台默认密码已修改；",
				"- 首页、关于页、开始使用页不再是演示文案；",
				"- 资源链接已经换成自己的项目入口；",
				"- `BASE_URL` 已设置成正式域名；",
				"- 数据库文件已经纳入备份。",
				"",
				"> 演示数据是脚手架，不是正式内容。上线前请拆掉脚手架。",
			),
		},
		{
			Slug: "first-launch-security-and-demo-data", Title: "After First Launch, Do These Two Things",
			Excerpt:  "Change the default admin password, then decide whether to keep editing the product demo or clear demo content and start clean.",
			MetaDesc: "A gcms first-launch safety guide: change the default admin password, understand reload product demo vs clear demo data, and avoid launching with default content.",
			Keywords: "gcms,first launch,default password,demo data,security settings", Author: "gcms", Cat: "guides", Date: "2026-06-13",
			Lang: "en", Group: "g-first-launch-security", Cover: "/assets/screenshots/security-demo-data-en.webp",
			Content: md(
				"On first launch, gcms writes a complete product demo so you can see the full site. Before going live, the first task is not writing posts; it is cleaning up security and demo data.",
				"",
				"![Real gcms screenshot: security settings with password change, reload product demo and clear demo data actions](/assets/screenshots/security-demo-data-en.webp)",
				"",
				"## First: change the default password",
				"The default account is for first-run onboarding and must not stay in production. Go to Settings → Security, enter the current password and a new one. Save, then log in again to confirm.",
				"",
				"## Second: decide what to do with demo data",
				"If you want to reshape the gcms product demo into your own official site, click Reload Product Demo. It restores the latest sample structure, then you can replace site name, navigation, posts, links and pages.",
				"",
				"If your own content is ready, click Clear Demo Data Only. It removes built-in posts, pages, links, categories and sample navigation, but keeps the admin account, password, logo, uploads, theme and base settings.",
				"",
				"## Pre-launch checklist",
				"- Default admin password changed;",
				"- Homepage, About and Get Started pages no longer use demo copy;",
				"- Resource links point to your own project entries;",
				"- `BASE_URL` is set to the production domain;",
				"- The SQLite database file is included in backups.",
				"",
				"> Demo data is scaffolding, not production content. Remove the scaffolding before launch.",
			),
		},
	}
}

// showcaseAbouts 返回产品页面（中英双语）。
func showcaseAbouts() []seedPost {
	return []seedPost{
		{
			Type: "page", Slug: "about", Title: "关于 gcms", Lang: "zh", Group: "s-page-about",
			Excerpt:  "gcms 面向产品官网、技术文档和轻量内容站：一个二进制启动，一个 SQLite 文件存数据，SEO 与多语种默认就绪。",
			MetaDesc: "gcms 是面向产品官网、技术文档和轻量内容站的自托管 CMS：单一静态二进制 + SQLite 单文件数据库，原生 SEO、多语种、18 套主题、在线更新与自动化接口。",
			Keywords: "gcms,关于,CMS,Go,SQLite,自托管", Author: "gcms", Date: "2026-06-12",
			Content: md(
				"**gcms** 是一个把「上线简单、长期维护简单」放在第一位的内容管理系统。它适合产品官网、技术文档、个人知识库、资源导航和轻量内容站。",
				"",
				"## 它解决什么",
				"很多内容站不缺功能，缺的是低维护：数据库服务要管、前端构建要管、SEO 细节要管、升级也要靠记命令。gcms 把这些收敛到一个二进制和一个数据库文件里，让小团队或个人也能长期安心运营。",
				"",
				"## 你会得到什么",
				"- 用 **Go + SQLite** 构建，最终是**一个静态二进制 + 一个数据库文件**；",
				"- 100% 服务端渲染，**原生 SEO**（canonical / hreflang / sitemap / JSON-LD）；",
				"- **多语种内容**、**18 套主题**、**Markdown ⇄ 富文本编辑器**、可视化站点配置；",
				"- 链接展示、页脚社交入口、代码注入、自定义导航、评论接入；",
				"- 跨平台启停脚本、Caddy 部署建议、**后台在线更新**与自动化 API。",
				"",
				"## 它的取舍",
				"gcms 不追求变成万能平台。它更像一个可靠的内容底座：没有独立数据库进程，没有前端构建链，没有运行时依赖。备份是复制一个文件，迁移是 `scp` 一个文件。把复杂留在编译期，把简单交给你。",
				"",
				"## 开始使用",
				"- 正式站点：[ccvar.com](https://ccvar.com)；",
				"- 下载发布包：[Releases](https://github.com/ccvar/gcms-releases/releases/latest)；",
				"- 一键安装：`curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`。",
				"",
				"> 工具应当隐形。当你不再注意到它，它才算做对了。",
			),
		},
		{
			Type: "page", Slug: "about", Title: "About gcms", Lang: "en", Group: "s-page-about",
			Excerpt:  "gcms is for product sites, docs and lightweight content hubs: one binary to run, one SQLite file for data, SEO and i18n ready by default.",
			MetaDesc: "gcms is a self-hosted CMS for product sites, docs and lightweight content hubs: one static binary, one SQLite database file, SEO-native, multilingual, 18 themes, in-app updates and automation APIs.",
			Keywords: "gcms,about,CMS,Go,SQLite,self-hosted", Author: "gcms", Date: "2026-06-12",
			Content: md(
				"**gcms** is a content management system built around one promise: launch simply, maintain simply. It fits product sites, docs, personal knowledge bases, resource directories and lightweight content hubs.",
				"",
				"## What it solves",
				"Many content sites don't lack features; they lack low maintenance. A database service to operate, a front-end build to manage, SEO details to remember, upgrades that require commands. gcms compresses that into one binary and one database file.",
				"",
				"## What you get",
				"- Built with **Go + SQLite**, shipped as **one static binary plus one database file**;",
				"- 100% server-rendered, **SEO-native** (canonical / hreflang / sitemap / JSON-LD);",
				"- **Multilingual content**, **18 themes**, **Markdown ⇄ WYSIWYG editor**, visual site configuration;",
				"- Link showcase, social footer, code injection, custom navigation and optional comments;",
				"- Cross-platform scripts, Caddy deployment guidance, **in-app updates** and automation APIs.",
				"",
				"## The trade-off",
				"gcms doesn't try to be a universal platform. It is a reliable content base: no separate database process, no frontend build chain, no runtime dependencies. Backup is copying one file; migration is `scp`-ing one file.",
				"",
				"## Get started",
				"- Official site: [ccvar.com](https://ccvar.com);",
				"- Downloads: [Releases](https://github.com/ccvar/gcms-releases/releases/latest);",
				"- One-line install: `curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`.",
				"",
				"> Tools should be invisible. When you stop noticing them, they're done right.",
			),
		},
		{
			Type: "page", Slug: "start", Title: "开始使用 gcms", Lang: "zh", Group: "s-page-start",
			Excerpt:  "想试用、部署或接入自动化？这里是最短路径：正式站点、发布包、一键安装和部署建议。",
			MetaDesc: "gcms 开始使用入口：访问正式站点 ccvar.com、下载发布包、一键安装、查看 Caddy 部署建议并反馈使用问题。",
			Keywords: "gcms,开始使用,支持,下载,部署", Author: "gcms", Date: "2026-06-12",
			Content: md(
				"如果你正在评估 **gcms**，最好的方式是先把它跑起来。它不需要额外数据库服务，也不需要前端构建链；下载后就是一个标准运行目录。",
				"",
				"## 快速试用",
				"- 正式站点：[ccvar.com](https://ccvar.com)",
				"- 下载发布包：[GitHub Releases](https://github.com/ccvar/gcms-releases/releases/latest)",
				"- 一键安装：`curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`",
				"",
				"## 环境要求",
				"gcms 不是重型平台，小规格服务器就能跑起来，适合先用很小的成本把产品官网、技术文档或资源导航上线。",
				"",
				"- **CPU**：1 vCPU 即可启动并支撑日常内容发布；",
				"- **内存**：512MB 级别 VPS 可以部署普通产品官网、文档站或资源导航；",
				"- **磁盘**：程序包很小，主要占用来自 SQLite 数据库、上传图片和日志；",
				"- **系统**：Linux、macOS、Windows 均提供 amd64 / arm64 发布包；",
				"- **公网入口**：生产环境推荐用 Caddy 监听 80/443，gcms 监听 `127.0.0.1:8080`。",
				"",
				"后续内容量或访问量变大，再按实际情况增加内存和磁盘即可。",
				"",
				"## 部署建议",
				"生产环境建议让 gcms 监听 `127.0.0.1:8080`，前面用 Caddy 负责 HTTPS、压缩和 HTTP/3。发布仓库中也提供了独立的 Caddy 安装与配置脚本。",
				"",
				"## 反馈问题",
				"如果遇到安装、升级或部署问题，请带上系统平台、gcms 版本、日志片段和复现步骤。信息越完整，问题越容易定位。",
			),
		},
		{
			Type: "page", Slug: "start", Title: "Start with gcms", Lang: "en", Group: "s-page-start",
			Excerpt:  "Trying, deploying or integrating gcms? Here are the shortest paths: official site, releases, one-line install and deployment notes.",
			MetaDesc: "gcms getting-started entry points: visit ccvar.com, download releases, run the one-line install, review Caddy deployment notes and report issues.",
			Keywords: "gcms,get started,support,download,deploy", Author: "gcms", Date: "2026-06-12",
			Content: md(
				"If you're evaluating **gcms**, the best next step is to run it. It needs no separate database service and no frontend build chain; the downloaded package is already a standard runtime directory.",
				"",
				"## Try it quickly",
				"- Official site: [ccvar.com](https://ccvar.com)",
				"- Downloads: [GitHub Releases](https://github.com/ccvar/gcms-releases/releases/latest)",
				"- One-line install: `curl -fsSL https://raw.githubusercontent.com/ccvar/gcms-releases/main/install.sh | sh`",
				"",
				"## Environment requirements",
				"gcms is not a heavy platform. A small server is enough to launch a product site, docs hub or resource directory before you scale up.",
				"",
				"- **CPU**: 1 vCPU is enough to start and handle normal publishing work;",
				"- **Memory**: a 512MB VPS can deploy a regular product site, docs site or resource directory;",
				"- **Disk**: the package is small; most growth comes from the SQLite database, uploads and logs;",
				"- **OS**: Linux, macOS and Windows packages are available for amd64 / arm64;",
				"- **Public entry**: in production, put Caddy on 80/443 and bind gcms to `127.0.0.1:8080`.",
				"",
				"When content volume or traffic grows, increase memory and disk based on real usage.",
				"",
				"## Deployment suggestion",
				"In production, bind gcms to `127.0.0.1:8080` and put Caddy in front for HTTPS, compression and HTTP/3. The release repository also includes standalone Caddy install and configuration scripts.",
				"",
				"## Report an issue",
				"When reporting installation, update or deployment issues, include your platform, gcms version, log snippets and steps to reproduce. The more complete the context, the faster the fix.",
			),
		},
	}
}

// showcaseLinks 返回项目生态链接（中英双语，置顶项用于首页「精选链接」与安装入口）。
func showcaseLinks() []seedPost {
	return []seedPost{
		// 中文
		{Type: "link", Slug: "github", Title: "发布仓库", Cat: "project", Lang: "zh", Group: "s-link-gh", Featured: true,
			LinkURL: "https://github.com/ccvar/gcms-releases", Date: "2026-06-12", Cover: "/assets/covers/release-repo-real.webp",
			Excerpt: "公开存放二进制发布包、安装脚本、校验文件与更新清单。", MetaDesc: "gcms 公开发布仓库", Keywords: "gcms,GitHub,发布,下载",
			Content: md(
				"gcms 的公开发布仓库只存放预编译二进制、安装脚本、校验文件和更新清单。源码仓库可以保持私有，用户仍然能下载、安装和在线升级。",
				"",
				"## 这里有什么",
				"- 各平台发布包：linux、macOS、windows，覆盖 amd64 与 arm64；",
				"- `manifest.json`：后台在线更新会读取的版本清单；",
				"- `checksums.txt`：下载后校验 SHA256，避免安装不完整文件；",
				"- `install.sh`、`setup-caddy.sh`：给新用户的一键安装与 Caddy 配置入口。",
			)},
		{Type: "link", Slug: "demo", Title: "正式站点", Cat: "project", Lang: "zh", Group: "s-link-demo", Featured: true,
			LinkURL: "https://ccvar.com", Date: "2026-06-12", Cover: "/assets/covers/site.webp",
			Excerpt: "ccvar.com 本身就是 gcms 产品演示站。", MetaDesc: "gcms 正式站点与在线演示", Keywords: "gcms,Demo,演示,ccvar",
			Content: md(
				"最好的介绍就是亲自用。ccvar.com 本身就跑在 gcms 上——你看到的首页、分类、文章、资源和多语种页面，都是它实时渲染的。",
				"",
				"这个站同时也是默认产品演示站的参考：用户下载 gcms 后，可以载入同样结构的内容，再按自己的品牌、主题、导航和文章体系改造成正式站点。",
			)},
		{Type: "link", Slug: "releases", Title: "下载发布包", Cat: "project", Lang: "zh", Group: "s-link-rel", Featured: true,
			LinkURL: "https://github.com/ccvar/gcms-releases/releases/latest", Date: "2026-06-11", Cover: "/assets/covers/release-package-real.webp",
			Excerpt: "各平台预编译部署包：下载、解压、运行。", MetaDesc: "gcms 各平台发布包下载", Keywords: "gcms,下载,发布包",
			Content: md(
				"各平台（linux / macOS / windows）的预编译部署包，内含二进制、启停脚本与默认配置。下载、解压、运行即可；后续也能通过后台在线升级。",
				"",
				"如果是生产部署，建议下载对应服务器架构的包，把 gcms 监听在 `127.0.0.1:8080`，前面交给 Caddy 做 HTTPS 与反向代理。这样应用升级、证书、压缩和域名入口各自清晰。",
			)},
		{Type: "link", Slug: "go", Title: "Go", Cat: "stack", Lang: "zh", Group: "s-link-go", Featured: true,
			LinkURL: "https://go.dev", Date: "2026-06-10", Cover: "/assets/covers/go-brand.webp",
			Excerpt: "让 gcms 可以交付为单一静态二进制。", MetaDesc: "Go 官网", Keywords: "Go,golang",
			Content: md("gcms 用 Go 构建：一次编译产出零依赖的静态二进制，交叉编译到各平台轻而易举。Go 的标准库、`embed.FS` 和清晰的部署形态，是 gcms 能把模板、静态资源和后端逻辑收敛到一个可执行文件里的关键。")},
		{Type: "link", Slug: "sqlite", Title: "SQLite", Cat: "stack", Lang: "zh", Group: "s-link-sqlite", Featured: true,
			LinkURL: "https://sqlite.org", Date: "2026-06-10", Cover: "/assets/covers/sqlite-brand.webp",
			Excerpt: "让数据、备份和迁移都收敛到一个文件。", MetaDesc: "SQLite 官网", Keywords: "SQLite,数据库",
			Content: md("gcms 的数据存在一个 SQLite 文件里：零配置、极可靠，备份就是复制一个文件。对读多写少的内容站来说，SQLite 的简单、稳定和低运维成本，比一开始引入独立数据库服务更实际。")},
		{Type: "link", Slug: "caddy", Title: "Caddy", Cat: "stack", Lang: "zh", Group: "s-link-caddy",
			LinkURL: "https://caddyserver.com", Date: "2026-06-09", Cover: "/assets/covers/caddy-brand.webp",
			Excerpt: "推荐的反向代理，自动 HTTPS。", MetaDesc: "Caddy 官网", Keywords: "Caddy,反向代理,HTTPS",
			Content: md("生产环境推荐用 Caddy 给 gcms 做反向代理：自动签发证书、HTTP/3 与压缩开箱即用。gcms 专注内容渲染和后台管理，Caddy 负责公网入口、TLS、压缩和域名转发，这个边界清晰也更容易排错。")},
		// 英文
		{Type: "link", Slug: "github", Title: "Release Repository", Cat: "project", Lang: "en", Group: "s-link-gh", Featured: true,
			LinkURL: "https://github.com/ccvar/gcms-releases", Date: "2026-06-12", Cover: "/assets/covers/release-repo-real-en.webp",
			Excerpt: "Public binaries, install scripts, checksums and update manifests.", MetaDesc: "gcms public release repository", Keywords: "gcms,GitHub,releases,downloads",
			Content: md(
				"The public gcms release repository only contains prebuilt binaries, install scripts, checksums and update manifests. The source repository can stay private while users can still download, install and upgrade in-app.",
				"",
				"## What's inside",
				"- Platform packages for linux, macOS and windows across amd64 and arm64;",
				"- `manifest.json`, read by in-app updates;",
				"- `checksums.txt`, used to verify SHA256 after download;",
				"- `install.sh` and `setup-caddy.sh`, the one-line install and Caddy setup entry points.",
			)},
		{Type: "link", Slug: "demo", Title: "Official Site", Cat: "project", Lang: "en", Group: "s-link-demo", Featured: true,
			LinkURL: "https://ccvar.com", Date: "2026-06-12", Cover: "/assets/covers/site-en.webp",
			Excerpt: "ccvar.com itself is the gcms product demo.", MetaDesc: "gcms official site and live demo", Keywords: "gcms,demo,ccvar",
			Content: md("The best introduction is to use it. ccvar.com itself runs on gcms — the homepage, categories, articles, resources and multilingual pages are all rendered by it. The same structure is available as the default product demo, so new users can load it and reshape it into their own official site.")},
		{Type: "link", Slug: "releases", Title: "Downloads", Cat: "project", Lang: "en", Group: "s-link-rel", Featured: true,
			LinkURL: "https://github.com/ccvar/gcms-releases/releases/latest", Date: "2026-06-11", Cover: "/assets/covers/release-package-real-en.webp",
			Excerpt: "Prebuilt packages for every platform.", MetaDesc: "gcms downloads for every platform", Keywords: "gcms,download,release",
			Content: md("Prebuilt deploy packages for linux / macOS / windows — binary, scripts and a default config. Download, unpack, run; upgrade later from the admin. In production, bind gcms to `127.0.0.1:8080` and let Caddy own HTTPS, compression and the public domain entry point.")},
		{Type: "link", Slug: "go", Title: "Go", Cat: "stack", Lang: "en", Group: "s-link-go", Featured: true,
			LinkURL: "https://go.dev", Date: "2026-06-10", Cover: "/assets/covers/go-brand-en.webp",
			Excerpt: "The language that lets gcms ship as one static binary.", MetaDesc: "The Go programming language", Keywords: "Go,golang",
			Content: md("gcms is built with Go: one compile yields a zero-dependency static binary, and cross-compiling to any platform is trivial. Go's standard library, `embed.FS` and clean deployment shape are what let gcms bundle templates, assets and backend logic into one executable.")},
		{Type: "link", Slug: "sqlite", Title: "SQLite", Cat: "stack", Lang: "en", Group: "s-link-sqlite", Featured: true,
			LinkURL: "https://sqlite.org", Date: "2026-06-10", Cover: "/assets/covers/sqlite-brand-en.webp",
			Excerpt: "The database that keeps data, backup and migration in one file.", MetaDesc: "SQLite official site", Keywords: "SQLite,database",
			Content: md("gcms keeps its data in a single SQLite file: zero-config, rock solid, and backup is copying one file. For read-heavy content sites, SQLite's simplicity, reliability and low operating cost are often more valuable than starting with a separate database service.")},
		{Type: "link", Slug: "caddy", Title: "Caddy", Cat: "stack", Lang: "en", Group: "s-link-caddy",
			LinkURL: "https://caddyserver.com", Date: "2026-06-09", Cover: "/assets/covers/caddy-brand-en.webp",
			Excerpt: "The recommended reverse proxy, automatic HTTPS.", MetaDesc: "Caddy web server", Keywords: "Caddy,reverse proxy,HTTPS",
			Content: md("In production, put Caddy in front of gcms as a reverse proxy: automatic certificates, HTTP/3 and compression out of the box. gcms focuses on content rendering and admin workflows; Caddy owns TLS, compression, public routing and domain handling.")},
	}
}
